### ISSUE TITLE
The project is using an incompatible preview version (AGP 8.2.0-alpha11) of the Android Gradle plugin. Current compatible version is AGP 8.4.1.

### ISSUE THREAD

**Issue by SauKaguya** [DawinderGill/MusicPlayer-JetpackCompose#3]
I use the latest version of Android Studio, Android Studio Jellyfish | 2023.3.1 Patch 1.

I'm a beginner and I searched a lot but can't figure out how to solve this problem.

I tried to install the Android Studio version you used, but could not find the beta version installation package.

please help me.

**Comment by SauKaguya** [comment]
![Uploading 1.png…]()

**Comment by SauKaguya** [comment]
![1](https://github.com/DawinderGill/MusicPlayer-JetpackCompose/assets/107797401/8f05aaa7-0f11-4dee-aed7-5dac11478629)

**Comment by DawinderGill** [comment]
This error message indicates that there is a compatibility issue between the version of Android Studio you are using and the Android Gradle plugin version (8.2.0-alpha11) specified in this project. So you need to upgrade the Android Gradle plugin to version 8.4.1.

I have used **buildSrc and kotlin DSL**  to manage all dependencies and plugins. That's why it's not upgrading automatically. This is a drawback of this approach. So you need to upgrade it manually.

To resolve this issue, you can try the following steps:

1. Goto **buildSrc > src > main > kotlin**
2. Find **Versions** file and upgrade **pluginAndroidApplication** with your gradle plugin version which is 8.4.1 (According to my understanding)
So this line would be like this: 
**const val pluginAndroidApplication = "8.4.1"**
3. Sync the project with Gradle files by clicking the "**Sync Now**" button in the top-right corner of the Android Studio window or by selecting **"File" > "Sync with Gradle Files"** from the menu.
4. If you still encounter issues, try invalidating the caches and restarting Android Studio: **"File" > "Invalidate Caches / Restart..." > "Invalidate and Restart".**

If you want to learn more about the dependency management approach I have used then [click here](https://medium.com/@dawinderapps/dependency-management-with-buildsrc-and-kotlin-dsl-f6826e2a2383) for a detailed explanation.

**Comment by SauKaguya** [comment]
> This error message indicates that there is a compatibility issue between the version of Android Studio you are using and the Android Gradle plugin version (8.2.0-alpha11) specified in this project. So you need to upgrade the Android Gradle plugin to version 8.4.1.
> 
> I have used **buildSrc and kotlin DSL** to manage all dependencies and plugins. That's why it's not upgrading automatically. This is a drawback of this approach. So you need to upgrade it manually.
> 
> To resolve this issue, you can try the following steps:
> 
> 1. Goto **buildSrc > src > main > kotlin**
> 2. Find **Versions** file and upgrade **pluginAndroidApplication** with your gradle plugin version which is 8.4.1 (According to my understanding)
>    So this line would be like this:
>    **const val pluginAndroidApplication = "8.4.1"**
> 3. Sync the project with Gradle files by clicking the "**Sync Now**" button in the top-right corner of the Android Studio window or by selecting **"File" > "Sync with Gradle Files"** from the menu.
> 4. If you still encounter issues, try invalidating the caches and restarting Android Studio: **"File" > "Invalidate Caches / Restart..." > "Invalidate and Restart".**
> 
> If you want to learn more about the dependency management approach I have used then [click here](https://medium.com/@dawinderapps/dependency-management-with-buildsrc-and-kotlin-dsl-f6826e2a2383) for a detailed explanation.

Thank you very much, I got it working properly although there is still a strange error. It does not affect the build

![image](https://github.com/DawinderGill/MusicPlayer-JetpackCompose/assets/107797401/54d237a9-7b46-4386-9c50-496d0891f6c7)
![image](https://github.com/DawinderGill/MusicPlayer-JetpackCompose/assets/107797401/9bf74d58-bc60-4bc6-b816-397736a4d0d6)

**Comment by DawinderGill** [comment]
That's just a warning. You can ignore it for now.
